### PR TITLE
Sticky feeling while switching target.

### PR DESCRIPTION
**Pull request by salarwalker**
Hi. Here's a sticky switching feature.

### CODE REVIEW

**Comment by mklabs** [comment]
Hi,

First of all, sorry for not noticing your PR before, I wasn't very active the last few months.

I'm currently in the process of integrating the system with a new game and upgrading it to 4.25, I'll test and integrate your changes while doing so.

Thank you for the PR. Appreciated.

**Comment by salarwalker** [comment]
Fine, it's just a little change during using your plugins.
Good luck for your next game. =w=

已从 Outlook Mobile<https://aka.ms/blhgte> 发送

________________________________

**Comment by mklabs** [comment]
I've done a fair bit of modifications to the system already, I'll merge in your PR to get the commits in and manually port back your changes into my modified version.

Thanks again!

**Comment by mklabs** [comment]
Merged in the Marketplace version!

I've also made a few modifications to enable / disable this feature in Blueprints (mainly a bool to go through your logic or the original one) and move the Delta variable from TargetActorWithAxisInput() method to a UPROPERTY()

**Comment by salarwalker** [comment]
Happy to see that help. Hope to use it in my next project

已从 Outlook Mobile<https://aka.ms/blhgte> 发送

________________________________

**Pull request merged**
